### PR TITLE
ex: Adds usage examples for Hacktoberfest

### PR DESCRIPTION
**Pull request by ChrisKeefe**
This PR is part of our 2022 Hacktoberfest team-wide sprint to add usage examples to all methods in each of our core distribution plugins. The methods examples have been added for are as follows:

```
denoise_16S
visualize_stats
```

### CODE REVIEW

**Comment by ChrisKeefe** [comment]
`denoise_16S` tests clean locally and renders at the CLI like so:
image

**Comment by ChrisKeefe** [comment]
It's a little concerning that this _isn't_ failing in CI. Based on [quality_filter's example](https://github.com/qiime2/q2-quality-filter/actions/runs/3317836987/jobs/5481120754#step:4:681), I would expect this to fail here ([1](https://github.com/qiime2/q2-deblur/blob/ad5b35537c6b14fe476b0af60e6d7984da7471eb/q2_deblur/_examples.py#L15), [2](https://github.com/qiime2/q2-deblur/blob/ad5b35537c6b14fe476b0af60e6d7984da7471eb/q2_deblur/_examples.py#L37)) until [this](https://github.com/qiime2/qiime2/pull/658) is merged.

**Comment by ebolyen** [comment]
Hey @ChrisKeefe, yeah this 100% should have failed. Looking at the diff, I have no explanation as to why it isn't. My first guess is the new test isn't getting collected, but I can't prove that without pulling everything down locally.

**Comment by lizgehret** [comment]
Yeah it definitely looks like this should be getting collected @ChrisKeefe - I'm going to pull this down locally and test it out, I'll let you know what I find!

**Comment by lizgehret** [comment]
Okay so this fails for me locally @ChrisKeefe - I'm going to re-run CI and see if that was just a weird one off, or if CI isn't running your examples for some reason.

**Comment by lizgehret** [comment]
Okay I figured out where the issue is coming from - we commented out the test commands for deblur back in June: https://github.com/qiime2/q2-deblur/commit/0bbcdc81f4554c9f65f354f894724654faf19821

Looks like we were waiting on [this PR](https://github.com/qiime2/q2-deblur/pull/91) to get merged before un-commenting our tests, so I'll cut a PR that reverts those comments and once that's merged I'll re-run this and we should see CI fail!

**Comment by lizgehret** [comment]
Okay so it's a bit more complicated than I was initially hoping - the PR I cut above (#95) is currently failing, and without having done a deep dive into it yet, it seems like these errors may be due to an incompatibility with deblur 1.1.1 (1.1.2 hasn't been released yet, and it's unclear when that will happen). I think the reason that things are failing locally but not on CI is that we are just running the tests directly vs. through action library packaging. The 'build' step isn't actually running the tests for deblur, and I think that's because of this PR (#91) - even though it looked like this was intended to still run tests, just through a python script vs. through the test commands block in q2-deblur's recipe file. Anyways - I'm going to investigate more tomorrow, but wanted to add the info that I have so far. cc @ebolyen

**Comment by lizgehret** [comment]
circling back on this - the `run_test.sh` file within the recipe folder is only testing deblur itself, not q2-deblur. i'm cutting a separate PR that adds in the additional-tests command to actually run q2-deblur's unit tests.

**Comment by lizgehret** [comment]
alright, now we've got test failures! 🥳 i'll get these URLs updated and then we should be all set with this one.

**Review by Oddant1 — APPROVED** [review]
lgtm

**Pull request merged**
