### PR TITLE
Updating numpy and scipy dependencies

### PR DESCRIPTION
**Pull request by mortonjt**
This updates numpy and scipy dependencies.  Mainly, I want to see what errors pop up if we bump up the version numbers

Addresses #68

### CODE REVIEW

**Comment by thermokarst** [comment]
Hey @mortonjt, this won't change the version of numpy included in the environment file, because there is still the version pin in scikit-bio.

**Comment by mortonjt** [comment]
yep - new changelog is posted here: https://github.com/biocore/scikit-bio/pull/1643/files

Am ready to push out new release on que

**Comment by mortonjt** [comment]
Hi @thermokarst , just as a heads up - scikit-bio has been updated!  Do you think we can bump up the pin to scikit-bio=0.5.5? Thanks!

**Comment by thermokarst** [comment]
Thanks @mortonjt, this was addressed in https://github.com/qiime2/q2-deblur/pull/76 (a slightly more comprehensive effort that also involved upgrading to python 3.6). Thanks!

**Comment by mortonjt** [comment]
Awesome!

**Pull request closed without merging**
