### PR TITLE
Bump minimum version req

### PR DESCRIPTION
**Pull request by wasade**
@thermokarst, I'm looking at doing a test case here but it'll need to be a bit contrived. Don't have a solution exactly yet.

### CODE REVIEW

**Comment by thermokarst** [comment]
Sorry @wasade for letting this sit for so long - I was traveling last week, but am back in the office now.

**Comment by thermokarst** [comment]
Thanks @wasade! Looks great! No worries on the tests.

**Comment by thermokarst** [comment]
[Busywork just failed](https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/integration/builds/41) on integration due to a hard version pin in this version of `deblur`:

```
UnsatisfiableError: The following specifications were found to be in conflict:
	
  - q2-alignment=2018.4.0.dev0 -> mafft[version='>=7.310']
	
  - q2-deblur=2018.4.0.dev0+1.g9d1c639 -> deblur[version='>=1.0.4'] -> mafft==7.221
```

Is there any way the deblur pin can be loosened up a bit?

**Comment by wasade** [comment]
No worries! And yes, see `https://github.com/biocore/deblur/blob/master/.travis.yml#L14`

**Comment by thermokarst** [comment]
Related PR available here: https://github.com/biocore/conda-recipes/pull/120

**Pull request merged**
