### PR TITLE
dep/bug: deblur doesn't work with click 8

### PR DESCRIPTION
**Pull request by thermokarst**
https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/unit-test-q2-deblur/builds/177

cc @wasade

### CODE REVIEW

**Comment by thermokarst** [comment]
I'm still confirming this right now, part of that confirmation is running the ci here in this PR. More soon...

**Comment by wasade** [comment]
Thanks, only thing that seems to stand out to is the use of a callback (e.g., https://github.com/biocore/deblur/blob/master/scripts/deblur#L478). Gonna look at the click changelog

**Comment by wasade** [comment]
Nothing remarkable from the changelog but didn't examine the issues directly. I think I spotted it though, it looks like an exception is raised [here](https://github.com/biocore/deblur/blob/master/scripts/deblur#L45), as the return type from the [default](https://github.com/biocore/deblur/blob/master/scripts/deblur#L70) is not of type [str](https://github.com/biocore/deblur/blob/4b4badccdbac8fe9d8f8b3f1349f3700e31b5d7b/deblur/deblurring.py#L21-L23)

...while I think the above _is_ erroneous, it suggests that the semantics for callbacks with Click 8 may have changed as it appears to be executing the callback even though the parameter wasn't specified (per the CircleCI output).

**Comment by thermokarst** [comment]
Thanks @wasade! I'll merge this PR for now. What can I do w.r.t. deblur's issue tracker so that we don't lose track of this?

**Comment by wasade** [comment]
Thanks! Would it be possible to create an issue and just link back to the discussion here? Will q2 2021.8 be relying on click 8 or is the plan to remain with 7.x?

**Comment by thermokarst** [comment]
I think we'll stick with click 7 for now - q2cli is also not working correctly with click 8 at the moment, and I'm inclined to give it a release cycle before tackling.

**Comment by wasade** [comment]
Makes sense, thanks!

**Pull request merged**
